// Shared & Live Event Error Codes
export const JUDGE_SUBMISSIONS_GET_ERROR = 'JUDGE_SUBMISSIONS_GET_ERROR';
export const ROUND_RESULTS_GET_ERROR = 'ROUND_RESULTS_GET_ERROR';
export const DECLARED_WINNERS_GET_ERROR = 'DECLARED_WINNERS_GET_ERROR';
export const ROUND_PHASE_NOT_FOUND = 'ROUND_PHASE_NOT_FOUND';
export const ROUND_ID_INVALID = 'ROUND_ID_INVALID';
export const FORBIDDEN = 'FORBIDDEN';

export const SELECTED_CONTESTANT_IDS_INVALID = 'SELECTED_CONTESTANT_IDS_INVALID';
export const SELECTED_CONTESTANT_ID_INVALID = 'SELECTED_CONTESTANT_ID_INVALID';
export const SELECTED_CONTESTANT_IDS_DUPLICATE = 'SELECTED_CONTESTANT_IDS_DUPLICATE';
export const SELECTED_CONTESTANT_IDS_NOT_ALLOWED = 'SELECTED_CONTESTANT_IDS_NOT_ALLOWED';
export const SELECTED_CONTESTANT_IDS_REQUIRED = 'SELECTED_CONTESTANT_IDS_REQUIRED';
export const SELECTED_CONTESTANT_IDS_COUNT_INVALID = 'SELECTED_CONTESTANT_IDS_COUNT_INVALID';
export const SELECTED_CONTESTANT_ID_NOT_IN_TIE_GROUP = 'SELECTED_CONTESTANT_ID_NOT_IN_TIE_GROUP';

export const ADVANCE_CONTESTANT_COUNT_MISMATCH = 'ADVANCE_CONTESTANT_COUNT_MISMATCH';
export const ADVANCE_NOT_ALLOWED = 'ADVANCE_NOT_ALLOWED';
export const ROUND_ADVANCEMENT_ERROR = 'ROUND_ADVANCEMENT_ERROR';

export const DECLARE_WINNER_COUNT_MISMATCH = 'DECLARE_WINNER_COUNT_MISMATCH';
export const DECLARE_NOT_ALLOWED = 'DECLARE_NOT_ALLOWED';
export const DECLARE_WINNERS_ERROR = 'DECLARE_WINNERS_ERROR';

// Judge Scoring Error Codes
export const SCORING_CATEGORY_ID_INVALID = 'SCORING_CATEGORY_ID_INVALID';
export const SCORING_CATEGORY_NOT_FOUND = 'SCORING_CATEGORY_NOT_FOUND';
export const SCORING_FIELDS_GET_ERROR = 'SCORING_FIELDS_GET_ERROR';
export const SCORING_SCORES_GET_ERROR = 'SCORING_SCORES_GET_ERROR';

export const SCORING_ROUND_ID_INVALID = 'SCORING_ROUND_ID_INVALID';
export const SCORING_ROUND_NOT_FOUND = 'SCORING_ROUND_NOT_FOUND';
export const SCORING_CONTESTANTS_GET_ERROR = 'SCORING_CONTESTANTS_GET_ERROR';
export const SCORING_ROUNDS_GET_ERROR = 'SCORING_ROUNDS_GET_ERROR';

export const SCORING_SCORES_REQUIRED = 'SCORING_SCORES_REQUIRED';
export const SCORING_SCORE_ENTRY_INVALID = 'SCORING_SCORE_ENTRY_INVALID';
export const SCORING_VALUE_INVALID = 'SCORING_VALUE_INVALID';
export const SCORING_DUPLICATE_ENTRY = 'SCORING_DUPLICATE_ENTRY';
export const SCORING_CATEGORY_NO_FIELDS = 'SCORING_CATEGORY_NO_FIELDS';
export const SCORING_ROUND_NO_CONTESTANTS = 'SCORING_ROUND_NO_CONTESTANTS';
export const SCORING_CONTESTANT_NOT_IN_ROUND = 'SCORING_CONTESTANT_NOT_IN_ROUND';
export const SCORING_FIELD_NOT_IN_CATEGORY = 'SCORING_FIELD_NOT_IN_CATEGORY';
export const SCORING_SCORES_INCOMPLETE = 'SCORING_SCORES_INCOMPLETE';
export const SCORING_VALUE_OUT_OF_RANGE = 'SCORING_VALUE_OUT_OF_RANGE';
export const SCORING_ALREADY_SUBMITTED = 'SCORING_ALREADY_SUBMITTED';
export const SCORING_ROUND_LOCKED = 'SCORING_ROUND_LOCKED';
export const SCORING_ROUND_COMPLETED = 'SCORING_ROUND_COMPLETED';
export const SCORING_SUBMIT_ERROR = 'SCORING_SUBMIT_ERROR';

export type JudgeScoringErrorCodes =
  | typeof JUDGE_SUBMISSIONS_GET_ERROR
  | typeof ROUND_RESULTS_GET_ERROR
  | typeof DECLARED_WINNERS_GET_ERROR
  | typeof ROUND_PHASE_NOT_FOUND
  | typeof ROUND_ID_INVALID
  | typeof FORBIDDEN
  | typeof SELECTED_CONTESTANT_IDS_INVALID
  | typeof SELECTED_CONTESTANT_ID_INVALID
  | typeof SELECTED_CONTESTANT_IDS_DUPLICATE
  | typeof SELECTED_CONTESTANT_IDS_NOT_ALLOWED
  | typeof SELECTED_CONTESTANT_IDS_REQUIRED
  | typeof SELECTED_CONTESTANT_IDS_COUNT_INVALID
  | typeof SELECTED_CONTESTANT_ID_NOT_IN_TIE_GROUP
  | typeof ADVANCE_CONTESTANT_COUNT_MISMATCH
  | typeof ADVANCE_NOT_ALLOWED
  | typeof ROUND_ADVANCEMENT_ERROR
  | typeof DECLARE_WINNER_COUNT_MISMATCH
  | typeof DECLARE_NOT_ALLOWED
  | typeof DECLARE_WINNERS_ERROR
  | typeof SCORING_CATEGORY_ID_INVALID
  | typeof SCORING_CATEGORY_NOT_FOUND
  | typeof SCORING_FIELDS_GET_ERROR
  | typeof SCORING_SCORES_GET_ERROR
  | typeof SCORING_ROUND_ID_INVALID
  | typeof SCORING_ROUND_NOT_FOUND
  | typeof SCORING_CONTESTANTS_GET_ERROR
  | typeof SCORING_ROUNDS_GET_ERROR
  | typeof SCORING_SCORES_REQUIRED
  | typeof SCORING_SCORE_ENTRY_INVALID
  | typeof SCORING_VALUE_INVALID
  | typeof SCORING_DUPLICATE_ENTRY
  | typeof SCORING_CATEGORY_NO_FIELDS
  | typeof SCORING_ROUND_NO_CONTESTANTS
  | typeof SCORING_CONTESTANT_NOT_IN_ROUND
  | typeof SCORING_FIELD_NOT_IN_CATEGORY
  | typeof SCORING_SCORES_INCOMPLETE
  | typeof SCORING_VALUE_OUT_OF_RANGE
  | typeof SCORING_ALREADY_SUBMITTED
  | typeof SCORING_ROUND_LOCKED
  | typeof SCORING_ROUND_COMPLETED
  | typeof SCORING_SUBMIT_ERROR;
