export const JUDGE_SUBMISSIONS_GET_ERROR = 'JUDGE_SUBMISSIONS_GET_ERROR';
export const ROUND_RESULTS_GET_ERROR = 'ROUND_RESULTS_GET_ERROR';
export const DECLARED_WINNERS_GET_ERROR = 'DECLARED_WINNERS_GET_ERROR';
export const ROUND_PHASE_NOT_FOUND = 'ROUND_PHASE_NOT_FOUND';
export const ROUND_ID_INVALID = 'ROUND_ID_INVALID';
export const FORBIDDEN = 'FORBIDDEN';

// Advance Round & Declare Winners
export const SELECTED_CONTESTANT_IDS_INVALID = 'SELECTED_CONTESTANT_IDS_INVALID';
export const SELECTED_CONTESTANT_ID_INVALID = 'SELECTED_CONTESTANT_ID_INVALID';
export const SELECTED_CONTESTANT_IDS_DUPLICATE = 'SELECTED_CONTESTANT_IDS_DUPLICATE';
export const SELECTED_CONTESTANT_IDS_NOT_ALLOWED = 'SELECTED_CONTESTANT_IDS_NOT_ALLOWED';
export const SELECTED_CONTESTANT_IDS_REQUIRED = 'SELECTED_CONTESTANT_IDS_REQUIRED';
export const SELECTED_CONTESTANT_IDS_COUNT_INVALID = 'SELECTED_CONTESTANT_IDS_COUNT_INVALID';
export const SELECTED_CONTESTANT_ID_NOT_IN_TIE_GROUP = 'SELECTED_CONTESTANT_ID_NOT_IN_TIE_GROUP';

// Declare Winners — placement tie resolution
export const PLACEMENT_ORDER_INVALID = 'PLACEMENT_ORDER_INVALID';
export const PLACEMENT_ORDER_ID_INVALID = 'PLACEMENT_ORDER_ID_INVALID';
export const PLACEMENT_ORDER_IDS_DUPLICATE = 'PLACEMENT_ORDER_IDS_DUPLICATE';
export const PLACEMENT_ORDER_NOT_ALLOWED = 'PLACEMENT_ORDER_NOT_ALLOWED';
export const PLACEMENT_ORDER_REQUIRED = 'PLACEMENT_ORDER_REQUIRED';
export const PLACEMENT_ORDER_MISMATCH = 'PLACEMENT_ORDER_MISMATCH';

export const ADVANCE_CONTESTANT_COUNT_MISMATCH = 'ADVANCE_CONTESTANT_COUNT_MISMATCH';
export const ADVANCE_NOT_ALLOWED = 'ADVANCE_NOT_ALLOWED';
export const ADVANCE_REQUIRES_CHAIRMAN = 'ADVANCE_REQUIRES_CHAIRMAN';
export const ROUND_ADVANCEMENT_ERROR = 'ROUND_ADVANCEMENT_ERROR';

export const DECLARE_WINNER_COUNT_MISMATCH = 'DECLARE_WINNER_COUNT_MISMATCH';
export const DECLARE_NOT_ALLOWED = 'DECLARE_NOT_ALLOWED';
export const DECLARE_REQUIRES_CHAIRMAN = 'DECLARE_REQUIRES_CHAIRMAN';
export const CHAIRMAN_ACTION_REQUIRES_TIE = 'CHAIRMAN_ACTION_REQUIRES_TIE';
export const DECLARE_WINNERS_ERROR = 'DECLARE_WINNERS_ERROR';

export type liveErrorCodes =
  | typeof JUDGE_SUBMISSIONS_GET_ERROR
  | typeof ROUND_RESULTS_GET_ERROR
  | typeof DECLARED_WINNERS_GET_ERROR
  | typeof ROUND_PHASE_NOT_FOUND
  | typeof ROUND_ID_INVALID
  | typeof FORBIDDEN
  | typeof SELECTED_CONTESTANT_IDS_INVALID
  | typeof SELECTED_CONTESTANT_ID_INVALID
  | typeof SELECTED_CONTESTANT_IDS_DUPLICATE
  | typeof SELECTED_CONTESTANT_IDS_NOT_ALLOWED
  | typeof SELECTED_CONTESTANT_IDS_REQUIRED
  | typeof SELECTED_CONTESTANT_IDS_COUNT_INVALID
  | typeof SELECTED_CONTESTANT_ID_NOT_IN_TIE_GROUP
  | typeof PLACEMENT_ORDER_INVALID
  | typeof PLACEMENT_ORDER_ID_INVALID
  | typeof PLACEMENT_ORDER_IDS_DUPLICATE
  | typeof PLACEMENT_ORDER_NOT_ALLOWED
  | typeof PLACEMENT_ORDER_REQUIRED
  | typeof PLACEMENT_ORDER_MISMATCH
  | typeof ADVANCE_CONTESTANT_COUNT_MISMATCH
  | typeof ADVANCE_NOT_ALLOWED
  | typeof ADVANCE_REQUIRES_CHAIRMAN
  | typeof ROUND_ADVANCEMENT_ERROR
  | typeof DECLARE_WINNER_COUNT_MISMATCH
  | typeof DECLARE_NOT_ALLOWED
  | typeof DECLARE_REQUIRES_CHAIRMAN
  | typeof CHAIRMAN_ACTION_REQUIRES_TIE
  | typeof DECLARE_WINNERS_ERROR;
