// General
export const CATEGORY_NAME_REQUIRED = 'CATEGORY_NAME_REQUIRED';
export const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';
export const CATEGORY_LOCKED = 'CATEGORY_LOCKED';

// Add
export const CATEGORY_ROUND_ID_REQUIRED = 'CATEGORY_ROUND_ID_REQUIRED';
export const ROUND_PHASE_NOT_FOUND = 'ROUND_PHASE_NOT_FOUND';
export const CATEGORY_ADD_ERROR = 'CATEGORY_ADD_ERROR';

// Get
export const CATEGORY_GET_LIST_ERROR = 'CATEGORY_GET_LIST_ERROR';

// Get Category By Id = Edit
export const CATEGORY_GET_BY_ID_ERROR = 'CATEGORY_GET_BY_ID_ERROR';

// Save Changes = Edit
export const CATEGORY_EDIT_ERROR = 'CATEGORY_EDIT_ERROR';

// Delete
export const CATEGORY_DELETE_ERROR = 'CATEGORY_DELETE_ERROR';

// Get Category Fields
export const CATEGORY_FIELDS_GET_ERROR = 'CATEGORY_FIELDS_GET_ERROR';

// Save Category Fields
export const CATEGORY_FIELDS_REQUIRED = 'CATEGORY_FIELDS_REQUIRED';
export const CATEGORY_FIELD_NAME_REQUIRED = 'CATEGORY_FIELD_NAME_REQUIRED';
export const CATEGORY_FIELD_MAX_VALUE_REQUIRED = 'CATEGORY_FIELD_MAX_VALUE_REQUIRED';
export const CATEGORY_FIELD_MAX_VALUE_INVALID = 'CATEGORY_FIELD_MAX_VALUE_INVALID';
export const CATEGORY_FIELDS_SAVE_ERROR = 'CATEGORY_FIELDS_SAVE_ERROR';
export const CATEGORY_FIELDS_TOTAL_INVALID = 'CATEGORY_FIELDS_TOTAL_INVALID';

export type CategoryErrorCodes =
  | typeof CATEGORY_FIELDS_TOTAL_INVALID
  | typeof CATEGORY_FIELD_MAX_VALUE_REQUIRED
  | typeof CATEGORY_FIELDS_SAVE_ERROR
  | typeof CATEGORY_FIELD_NAME_REQUIRED
  | typeof CATEGORY_FIELD_MAX_VALUE_INVALID
  | typeof CATEGORY_FIELDS_REQUIRED
  | typeof CATEGORY_FIELDS_GET_ERROR
  | typeof CATEGORY_NAME_REQUIRED
  | typeof CATEGORY_ROUND_ID_REQUIRED
  | typeof ROUND_PHASE_NOT_FOUND
  | typeof CATEGORY_ADD_ERROR
  | typeof CATEGORY_GET_LIST_ERROR
  | typeof CATEGORY_NOT_FOUND
  | typeof CATEGORY_GET_BY_ID_ERROR
  | typeof CATEGORY_LOCKED
  | typeof CATEGORY_EDIT_ERROR
  | typeof CATEGORY_DELETE_ERROR
  | typeof CATEGORY_FIELDS_SAVE_ERROR;
