// GENERAL
export const JUDGE_NAME_TOO_SHORT = 'JUDGE_NAME_TOO_SHORT';
export const JUDGE_USERNAME_TOO_SHORT = 'JUDGE_USERNAME_TOO_SHORT';
export const JUDGE_PASSWORD_TOO_SHORT = 'JUDGE_PASSWORD_TOO_SHORT';
export const JUDGE_USERNAME_EXISTS = 'JUDGE_USERNAME_EXISTS';
export const JUDGE_NOT_FOUND = 'JUDGE_NOT_FOUND';

// GET LIST JUDGE
export const JUDGE_GET_LIST_FAILED = 'JUDGE_GET_LIST_FAILED';

// ADD JUDGE
export const JUDGE_ADD_FAILED = 'JUDGE_ADD_FAILED';

// EDIT JUDGE
export const JUDGE_EDIT_FAILED = 'JUDGE_EDIT_FAILED';

// RESET PASSWORD
export const JUDGE_RESET_PASSWORD_FAILED = 'JUDGE_RESET_PASSWORD_FAILED';

// DELETE JUDGE
export const JUDGE_DELETE_FAILED = 'JUDGE_DELETE_FAILED';
export const JUDGE_LOCKED = 'JUDGE_LOCKED';

export type JudgeErrorCodes =
  | typeof JUDGE_DELETE_FAILED
  | typeof JUDGE_LOCKED
  | typeof JUDGE_RESET_PASSWORD_FAILED
  | typeof JUDGE_NOT_FOUND
  | typeof JUDGE_EDIT_FAILED
  | typeof JUDGE_NAME_TOO_SHORT
  | typeof JUDGE_USERNAME_TOO_SHORT
  | typeof JUDGE_PASSWORD_TOO_SHORT
  | typeof JUDGE_USERNAME_EXISTS
  | typeof JUDGE_GET_LIST_FAILED
  | typeof JUDGE_ADD_FAILED;
