export const INVALID_USERNAME = 'INVALID_USERNAME';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

export type AuthErrorCodes =
  typeof INVALID_USERNAME | typeof INVALID_PASSWORD | typeof INVALID_CREDENTIALS;
