// GET CONTESTANTS
export const CONTESTANT_FILTER_INVALID = 'CONTESTANT_FILTER_INVALID';
export const CONTESTANT_GET_ALL_ERROR = 'CONTESTANT_GET_ALL_ERROR';

// ADD CONTESTANTS
export const CONTESTANT_CANDIDATE_NUMBER_REQUIRED = 'CONTESTANT_CANDIDATE_NUMBER_REQUIRED';
export const CONTESTANT_CANDIDATE_NUMBER_DUPLICATE = 'CONTESTANT_CANDIDATE_NUMBER_DUPLICATE';
export const CONTESTANT_NAME_REQUIRED = 'CONTESTANT_NAME_REQUIRED';
export const CONTESTANT_GENDER_REQUIRED = 'CONTESTANT_GENDER_REQUIRED';
export const CONTESTANT_GENDER_INVALID = 'CONTESTANT_GENDER_INVALID';
export const CONTESTANT_TEAM_NAME_REQUIRED = 'CONTESTANT_TEAM_NAME_REQUIRED';
export const CONTESTANT_TEAM_COLOR_REQUIRED = 'CONTESTANT_TEAM_COLOR_REQUIRED';
export const CONTESTANT_ADD_ERROR = 'CONTESTANT_ADD_ERROR';

// DELETE CONTESTANTS
export const CONTESTANT_LOCKED = 'CONTESTANT_LOCKED';
export const CONTESTANT_NOT_FOUND = 'CONTESTANT_NOT_FOUND';

export type ContestantsErrorCodes =
  | typeof CONTESTANT_NOT_FOUND
  | typeof CONTESTANT_LOCKED
  | typeof CONTESTANT_FILTER_INVALID
  | typeof CONTESTANT_GET_ALL_ERROR
  | typeof CONTESTANT_CANDIDATE_NUMBER_REQUIRED
  | typeof CONTESTANT_CANDIDATE_NUMBER_DUPLICATE
  | typeof CONTESTANT_NAME_REQUIRED
  | typeof CONTESTANT_GENDER_REQUIRED
  | typeof CONTESTANT_GENDER_INVALID
  | typeof CONTESTANT_TEAM_NAME_REQUIRED
  | typeof CONTESTANT_TEAM_COLOR_REQUIRED
  | typeof CONTESTANT_ADD_ERROR;
