// GET CONTESTANTS
export const CONTESTANT_FILTER_INVALID = 'CONTESTANT_FILTER_INVALID';
export const CONTESTANT_GET_ALL_ERROR = 'CONTESTANT_GET_ALL_ERROR';

export type ContestantsErrorCodes =
  typeof CONTESTANT_FILTER_INVALID | typeof CONTESTANT_GET_ALL_ERROR;
