import { defineStore } from 'pinia';
import type { FilterButtons, CandidatesItems } from '@/types/candidates/candidates';

export const useCandidateStore = defineStore('candidateStore', () => {
  const genderFilterButtons: FilterButtons[] = [
    { label: 'All', value: undefined },
    { label: 'Male', value: 'MALE' },
    { label: 'Female', value: 'FEMALE' },
  ];

  const malesCandidatesItems: CandidatesItems[] = [
    {
      canPicture: '/Males/candidate1.jpg',
      canNumber: 'No.1',
      canName: 'Louie Alangilan',
      canTeamLogo: '/TeamLogo/black_stallion.png',
      canCourse: 'SHS',
      canTeamName: 'Black Stallion',
      canTeamColor: '#000000',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate2.jpg',
      canNumber: 'No.2',
      canName: 'David Imanuel Senador',
      canTeamLogo: '/TeamLogo/white_wolves.png',
      canCourse: 'SHS',
      canTeamName: 'White Wolves',
      canTeamColor: '#ffffff',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate3.jpg',
      canNumber: 'No.3',
      canName: 'Rey Eldrine Paniza',
      canTeamLogo: '/TeamLogo/white_wolves.png',
      canCourse: 'BSIT',
      canTeamName: 'White Wolves',
      canTeamColor: '#ffffff',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate4.jpg',
      canNumber: 'No.4',
      canName: 'Froilan Nuhay',
      canTeamLogo: '/TeamLogo/purple_hawk.png',
      canCourse: 'BSIT',
      canTeamName: 'Purple Hawk',
      canTeamColor: '#c27aff',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate5.jpg',
      canNumber: 'No.5',
      canName: 'Gabriel Ramiso',
      canTeamLogo: '/TeamLogo/green_dragon.png',
      canCourse: 'BSIT',
      canTeamName: 'Green Dragon',
      canTeamColor: '#05df72',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate6.jpg',
      canNumber: 'No.6',
      canName: 'John Israel Miguel',
      canTeamLogo: '/TeamLogo/red_vipers.png',
      canCourse: 'BSIT',
      canTeamName: 'Red Vipers',
      canTeamColor: '#ff6467',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate7.jpg',
      canNumber: 'No.7',
      canName: 'John Caleb Lopez',
      canTeamLogo: '/TeamLogo/green_dragon.png',
      canCourse: 'BSIS',
      canTeamName: 'Green Dragon',
      canTeamColor: '#05df72',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate8.jpg',
      canNumber: 'No.8',
      canName: 'Jade Azryll Rubia',
      canTeamLogo: '/TeamLogo/purple_hawk.png',
      canCourse: 'BSHM',
      canTeamName: 'Purple Hawk',
      canTeamColor: '#c27aff',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate9.jpg',
      canNumber: 'No.9',
      canName: 'Kiann Jay Cañete',
      canTeamLogo: '/TeamLogo/black_stallion.png',
      canCourse: 'BSHM',
      canTeamName: 'Black Stallion',
      canTeamColor: '#000000',
      canGender: 'MALE',
    },
    {
      canPicture: '/Males/candidate10.jpg',
      canNumber: 'No.10',
      canName: 'Ralph Louie Chan',
      canTeamLogo: '/TeamLogo/red_vipers.png',
      canCourse: 'BSIS',
      canTeamName: 'Red Vipers',
      canTeamColor: '#ff6467',
      canGender: 'MALE',
    },
  ];

  const femalesCandidatesItems: CandidatesItems[] = [
    {
      canPicture: '/Females/candidate1.jpg',
      canNumber: 'No.1',
      canName: 'Venus Nicole Ferrer',
      canTeamLogo: '/TeamLogo/black_stallion.png',
      canCourse: 'BSOA',
      canTeamName: 'Black Stallion',
      canTeamColor: '#000000',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate2.jpg',
      canNumber: 'No.2',
      canName: 'Laarni Vergara',
      canTeamLogo: '/TeamLogo/white_wolves.png',
      canCourse: 'SHS',
      canTeamName: 'White Wolves',
      canTeamColor: '#ffffff',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate3.jpg',
      canNumber: 'No.3',
      canName: 'Jade Cabuenas',
      canTeamLogo: '/TeamLogo/white_wolves.png',
      canCourse: 'BSIT',
      canTeamName: 'White Wolves',
      canTeamColor: '#ffffff',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate4.jpg',
      canNumber: 'No.4',
      canName: 'Princess Jamaica Susing',
      canTeamLogo: '/TeamLogo/purple_hawk.png',
      canCourse: 'BSHM',
      canTeamName: 'Purple Hawk',
      canTeamColor: '#c27aff',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate5.jpg',
      canNumber: 'No.5',
      canName: 'Rhean Faith Orca',
      canTeamLogo: '/TeamLogo/green_dragon.png',
      canCourse: 'BSHM',
      canTeamName: 'Green Dragon',
      canTeamColor: '#05df72',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate6.jpg',
      canNumber: 'No.6',
      canName: 'Carmela Samonte',
      canTeamLogo: '/TeamLogo/red_vipers.png',
      canCourse: 'BSOA',
      canTeamName: 'Red Vipers',
      canTeamColor: '#ff6467',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate7.jpg',
      canNumber: 'No.7',
      canName: 'Jean Ryaen Felipe',
      canTeamLogo: '/TeamLogo/green_dragon.png',
      canCourse: 'BSHM',
      canTeamName: 'Green Dragon',
      canTeamColor: '#05df72',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate8.jpg',
      canNumber: 'No.8',
      canName: 'Althea Panagsagan',
      canTeamLogo: '/TeamLogo/purple_hawk.png',
      canCourse: 'BSHM',
      canTeamName: 'Purple Hawk',
      canTeamColor: '#c27aff',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate9.jpg',
      canNumber: 'No.9',
      canName: 'Yashira Coleen Sena',
      canTeamLogo: '/TeamLogo/black_stallion.png',
      canCourse: 'SHS',
      canTeamName: 'Black Stallion',
      canTeamColor: '#000000',
      canGender: 'FEMALE',
    },
    {
      canPicture: '/Females/candidate10.jpg',
      canNumber: 'No.10',
      canName: 'Alleria Bernardo',
      canTeamLogo: '/TeamLogo/red_vipers.png',
      canCourse: 'BSOA',
      canTeamName: 'Red Vipers',
      canTeamColor: '#ff6467',
      canGender: 'FEMALE',
    },
  ];
  return { genderFilterButtons, malesCandidatesItems, femalesCandidatesItems };
});
