// General Error Rounds
export const ROUND_NAME_INVALID = 'ROUND_NAME_INVALID';
export const ROUND_PHASE_ORDER_INVALID = 'ROUND_PHASE_ORDER_INVALID';
export const ROUND_CONTESTANT_LIMIT_INVALID = 'ROUND_CONTESTANT_LIMIT_INVALID';
export const ROUND_PHASE_NOT_FOUND = 'ROUND_PHASE_NOT_FOUND';

// Add
export const ROUND_PHASE_NO_PRELIMINARY_ROUND_EXISTS = 'ROUND_PHASE_NO_PRELIMINARY_ROUND_EXISTS';
export const ROUND_PHASE_ORDER_ALREADY_EXISTS = 'ROUND_PHASE_ORDER_ALREADY_EXISTS';
export const ROUND_PHASE_ORDER_DUPLICATE = 'ROUND_PHASE_ORDER_DUPLICATE';
export const ROUND_CONTESTANT_LIMIT_REQUIRED = 'ROUND_CONTESTANT_LIMIT_REQUIRED';
export const ROUND_PHASE_ADD_ERROR = 'ROUND_PHASE_ADD_ERROR';

// Edit
export const ROUND_ID_INVALID = 'ROUND_ID_INVALID';
export const ROUND_CONTESTANT_LIMIT_LOCKED = 'ROUND_CONTESTANT_LIMIT_LOCKED';
export const ROUND_PRELIMINARY_LIMIT_LOCKED = 'ROUND_PRELIMINARY_LIMIT_LOCKED';
export const ROUND_PHASE_EDIT_ERROR = 'ROUND_PHASE_EDIT_ERROR';
export const ROUND_PHASE_GET_BY_ID_ERROR = 'ROUND_PHASE_GET_BY_ID_ERROR';

// Delete
export const ROUND_PHASE_CATEGORY_LOCKED = 'ROUND_PHASE_CATEGORY_LOCKED';
export const ROUND_PHASE_HAS_CONTESTANTS = 'ROUND_PHASE_HAS_CONTESTANTS';
export const ROUND_PHASE_DELETE_ERROR = 'ROUND_PHASE_DELETE_ERROR';

// Get
export const ROUND_PHASE_GET_LIST_ERROR = 'ROUND_PHASE_GET_LIST_ERROR';

export type RoundErrorCodes =
  | typeof ROUND_NAME_INVALID
  | typeof ROUND_PHASE_ORDER_INVALID
  | typeof ROUND_CONTESTANT_LIMIT_INVALID
  | typeof ROUND_PHASE_NO_PRELIMINARY_ROUND_EXISTS
  | typeof ROUND_PHASE_ORDER_ALREADY_EXISTS
  | typeof ROUND_PHASE_ORDER_DUPLICATE
  | typeof ROUND_CONTESTANT_LIMIT_REQUIRED
  | typeof ROUND_PHASE_ADD_ERROR
  | typeof ROUND_ID_INVALID
  | typeof ROUND_CONTESTANT_LIMIT_LOCKED
  | typeof ROUND_PRELIMINARY_LIMIT_LOCKED
  | typeof ROUND_PHASE_EDIT_ERROR
  | typeof ROUND_PHASE_NOT_FOUND
  | typeof ROUND_PHASE_GET_BY_ID_ERROR
  | typeof ROUND_PHASE_CATEGORY_LOCKED
  | typeof ROUND_PHASE_HAS_CONTESTANTS
  | typeof ROUND_PHASE_DELETE_ERROR
  | typeof ROUND_PHASE_GET_LIST_ERROR;
